package com.vincentderk.acircuitminer.miner.canonical;

/**
 * A result object generated by {@link EdgeCanonical}. 
 * It consists of the {@link #code}, {@link #lastVerticesOrdered} and {@link #inputCount}.
 *
 * @author Vincent Derkinderen
 * @version 1.0
 */
public class CodeOccResult {

    public CodeOccResult(long[] code, int[] lastVerticesOrdered, int inputCount) {
        this.code = code;
        this.lastVerticesOrdered = lastVerticesOrdered;
        this.inputCount = inputCount;
    }

    /**
     * The vertices of the state that was used to generate this result.
     * These are in order of assigned id, corresponding to their id in the code.
     */
    public int[] lastVerticesOrdered;
    
    /**
     * The generated code
     */
    public long[] code;
    
    /**
     * Amount of inputs
     */
    public int inputCount;
}
